---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  document-start: disable
  trailing-spaces: error
  new-line-at-end-of-file: enable
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-before: 0
    min-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1

ignore: |
  .git/
  node_modules/
  vendor/
